version: '3'


services:

    backend:
        build:
            context: ../backend
            dockerfile: ../backend/Dockerfile
        ports:
            - "8000:8000"
        depends_on:
            -   db
        volumes:
            -   ../backend/src:/backend/src

    db:
        image: postgres:15.6-bullseye
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
            POSTGRES_PORT: 5432
            POSTGRES_HOST: localhost
