"""init

Revision ID: ec5bf34b0574
Revises: 
Create Date: 2024-09-22 23:20:30.321517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'ec5bf34b0574'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('ticket',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('phone_number', sa.String(), nullable=False),
                    sa.Column('issue_date', sa.DATE(), nullable=False),
                    sa.Column('return_date', sa.DATE(), nullable=True),
                    sa.Column('comment', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('inventory_in_ticket',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('inventory_id', sa.Integer(), nullable=True),
                    sa.Column('ticket_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['inventory_id'],
                                            ['inventory.id'], ),
                    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_in_ticket')
    op.drop_table('ticket')
    op.drop_table('inventory')
    # ### end Alembic commands ###
